### PR TITLE
Migrate to Terraform Plugin SDK

### PR DESCRIPTION
**Pull request by nikolay**

### CODE REVIEW

**Comment by yannh** [comment]
Hi Nokolay, that's awesome, I started looking into this but did not find the time to complete it yet :)

**Comment by nikolay** [comment]
By the way, @yannh, it was all done automatically. All I had to do manually is update the old terraform reference to 0.12.7 as anything below that was not supported. So, I upgraded the dependency, built it successfully, and then ran the [migrator]( https://github.com/hashicorp/tf-sdk-migrator).

**Comment by yannh** [comment]
Thanks, I'll give this a shot.

**Comment by yannh** [comment]
Finally moved to the plugin SDK v2 here https://github.com/yannh/terraform-provider-statuspage/pull/44 .. Thanks for pointing me to the right resources :)

**Pull request closed without merging**
